# Generated by Django 5.2 on 2025-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('api', '0002_profile_uuid_alter_appearance_body_type_mine_and_more'),
]
    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
