name: tadpool_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  cupertino_icons: ^1.0.4
  cupertino_tabbar: ^2.0.0
  dotted_border: ^2.0.0+2
  flutter_mobx: ^2.0.5
  flutter_svg: ^2.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intro_slider: ^4.2.1
  mobx: ^2.0.7
  notification_permissions: ^0.6.1
  provider: ^6.1.5
  shared_preferences: ^2.0.13
  # awesome_select: ^6.0.0
  flutter_awesome_select_clone: 7.5.0
  smart_select: ^4.3.0
  yaml: ^3.0.0
  permission_handler: ^12.0.0+1
  flutter_radar_chart: ^0.2.1
  geolocator: ^14.0.0
  flutter_config: ^2.0.0
  google_maps_flutter: ^2.0.11
  dio: ^5.8.0+1
  responsive_grid: ^2.1.0
  firebase_core_platform_interface: ^5.4.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.7
  file_picker: ^5.3.2
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.1.0
  #native_notify: ^0.0.17

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/discount.svg
    - assets/images/gifts.svg
    - assets/images/smiley_face.svg
    - assets/images/green_background.png
    - assets/lang/en.yaml
    - assets/images/login_bg.png
    - assets/images/match_profile.png
    - assets/images/match_profilev.png
    - assets/images/profile.svg
    - assets/images/add_photo.svg
    - assets/images/green-love.png
    - assets/images/froggy.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
